name: Build kubectl latest

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag - defaults to latest'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the webserver
        run: cd ${GITHUB_WORKSPACE}/kubectl/ && docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t larsnieuwenhuizen/kubectl:${{ github.event.inputs.tag }} . --push
