name: Build php images

on:
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Install pcregrep
        run: sudo apt install -y pcregrep

      - name: Enable buildx
        run: docker buildx create --use

      - name: Build and push images
        run: cd php && ./build.sh
